"""empty message

Revision ID: 9f8f2dbf8b41
Revises: e45f050f4955
Create Date: 2024-11-08 13:10:34.301803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f8f2dbf8b41'
down_revision = 'e45f050f4955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('draft', 'active', 'closed', name='status'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('draft', 'active', 'closed', name='status'),
               nullable=True)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
